# $\mathfrak{QMatch}$

In this tutorial, we introduce the package QMatch by 
- listing all functions
- explaining their inputs & outputs
- giving examples and some cross-checks

## Function List

### Functions that are general 
- correlation_mat(M: ndarray) -> ndarray
- 

### Functions for critical Ising
- Ising_Hamiltonian_mat(L)
- Ising_correlation_mat(L)
- 

## Import the package

In [1]:
from QMatch import *

#### import other packages needed for demonstrations

In [2]:
import numpy as np
from numpy import linalg as LA

## $\color{purple}{\rm Function:}$ correlation_mat(M: ndarray) -> ndarray
Given a free fermion Hamiltonian taking the following form,
\begin{equation}
H ~=~ \frac{i}{2}\,\sum_{i,j=1}^{2L}\,M_{ij}\,\gamma_i\,\gamma_j
\end{equation}
Input: 
- the matrix $M$: ndarray 

Output: 
- the correlation matrix for the ground state of $H$: ndarray

### $\color{green}{\rm Example:}$ 
here we compute the correlation matrix of critical Ising ground state with the system size $L$, thus the output is a $2L\times 2L$ antisymmetric matrix. 

First, we need the matrix $M$ for the critical Ising Hamiltonian with the system size L. The Hamiltonian reads
$$
H_{\rm Ising} ~=~ \frac{i}{2} \sum_{k=1}^{2L} \Big[ \gamma_k \gamma_{k+1} - \gamma_{k+1} \gamma_k \Big] 
$$
with periodic boundary condition $\gamma_{2L+1} = - \gamma_1$

In [3]:
correlation_mat(Ising_Hamiltonian_mat(L = 3))

array([[ 0.        , -0.66666667,  0.        , -0.33333333,  0.        ,
        -0.66666667],
       [ 0.66666667,  0.        , -0.66666667,  0.        , -0.33333333,
         0.        ],
       [ 0.        ,  0.66666667,  0.        , -0.66666667,  0.        ,
        -0.33333333],
       [ 0.33333333,  0.        ,  0.66666667,  0.        , -0.66666667,
         0.        ],
       [ 0.        ,  0.33333333,  0.        ,  0.66666667,  0.        ,
        -0.66666667],
       [ 0.66666667,  0.        ,  0.33333333,  0.        ,  0.66666667,
         0.        ]])

### $\color{green}{\rm Cross-check:}$ 
check correlation matrix of critical Ising ground state 
We compare the result obtained by the function correlation_mat with the analytic result for the correlation matrix of critical Ising ground state with the system size $L$, which is 
$$
G^{\rm Ising}_{jl} ~=~ 
    \begin{cases}
        0 \qquad\qquad\qquad\quad j-l~\text{is even} \\
        1/\left[L\, \sin\frac{\pi}{2L}(j-l) \right] ~~ j-l~\text{is odd} \\
    \end{cases}
$$

In [4]:
np.allclose(correlation_mat(Ising_Hamiltonian_mat(L=10)), Ising_correlation_mat(L=10))

True

## $\color{purple}{\rm Function:}$ ground_state_energy(M)
Input: the matrix $M$ in the Hamiltonian $$H ~=~ \frac{i}{2}\,\sum_{i,j=1}^{2L}\,M_{ij}\,\gamma_i\,\gamma_j$$ 

Output: the ground state energy $E_{\rm GS}$

### $\color{green}{\rm Example:}$ 
ground state energy for critical Ising with system size $L$

In [5]:
ground_state_energy(Ising_Hamiltonian_mat(L = 3))

-4.0

### $\color{green}{\rm Cross-check:}$ 
check the ground state energy result 

Again, we consider the critical Ising model with $L$ spins. Its Hamiltonian reads
$$
H_{\rm critical~Ising} ~=~ -\,\sum_{i=1}^L\left( X_i\,X_{i+1} + Z_i \right)
$$

In [6]:
eigv = LA.eigvalsh(Ising_H_def(L=3, g=1))
print(eigv[0])

-4.0


## $\color{purple}{\rm Function:}$ get_Grho_A(Grho, siteL, siteR)
This function computes the correlation matrix $G^{\rho_A}$ for a reduced density matrix $\rho_A$.

Inputs: 
- G_rho: the correlation matrix $G^{\rho}$ for $\rho$, which is a $2L\times2L$ matrix, namely the system is composed by $L$ spins
- siteL: the region $A$ starts from the $({\rm siteL}-1)$-th spin, siteL $\in [0,L-1]$
- siteR: the region $A$ ends at the siteR-th spin, siteR $\in [1,L]$

Output: 
- the correlation matrix for $\rho_A$

### $\color{green}{\rm Example:}$ 
consider critical Ising ground state with $L = 3$ and subregion $A$ is the first spin.  Thus the resulting correlation matrix should be the first $2x2$ block, i.e. 
$$
\begin{pmatrix}
0 & -2/3\\
2/3 & 0 
\end{pmatrix}
$$

In [7]:
G_rho = correlation_mat(Ising_Hamiltonian_mat(L = 3))
get_Grho_A(G_rho, 0, 1)

array([[ 0.        , -0.66666667],
       [ 0.66666667,  0.        ]])

## $\color{purple}{\rm Function:}$ tensor_prod(G1, G2)
This function compute the correlation matrix for a tensor product state. 

Inputs:
- G1: the correlation matrix $G^{\rho_1}$ for $\rho_1$
- G2: the correlation matrix $G^{\rho_2}$ for $\rho_2$

Output: 
- the correlation matrix $G^{\rho_1\otimes\rho_2}$ for $\rho_1\otimes\rho_2$

### $\color{green}{\rm Example:}$ 
consider 
- $\rho_1$ is the reduced density matrix for critical Ising ground state with $L=3$ and subregion $A$ is the first spin. Namely, 
$$ G^{\rho_1} ~=~ 
\begin{pmatrix}
0 & -2/3\\
2/3 & 0 
\end{pmatrix}
$$
- $\rho_2 = \frac{1}{2}\mathbb{I}_2$. Thus $G^{\rho_2}$ is a zero matrix, 
$$
G^{\rho_2} ~=~ 
\begin{pmatrix}
0 & 0\\
0 & 0 
\end{pmatrix}
$$

The result should be 
$$
G^{\rho_1\otimes \rho_2} ~=~ 
\begin{pmatrix}
0 & -2/3 & 0 & 0\\
2/3 & 0  & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
\end{pmatrix}
$$

In [8]:
G_rho = correlation_mat(Ising_Hamiltonian_mat(L = 3))
G1 = get_Grho_A(G_rho, 0, 1)
G2 = np.zeros([2,2])
tensor_prod(G1, G2)

array([[ 0.        , -0.66666667,  0.        ,  0.        ],
       [ 0.66666667,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

## $\color{purple}{\rm Function:}$ vn_entropy(Grho)
This function compute the von Neumann Entropy. 

Input: 
- the correlation matrix $G^{\rho}$ for the state $\rho$

Output: 
- the von Neumann Entropy for the state $\rho$, i.e.
$$S(\rho)=-{\rm Tr}(\rho\log\rho)$$

### $\color{green}{\rm Example:}$ 
Consider $\rho$ to be crtical Ising ground state with $L=10$, and its reduced density matrix $\rho_A$ where $L_A = 5$. 

In [9]:
G_rho = correlation_mat(Ising_Hamiltonian_mat(L = 10))
G_rho_A = get_Grho_A(G_rho, 0, 5)

Since now $\rho$ is a pure state, it has vanishing entropy. 

In [10]:
vn_entropy(G_rho)

0

For $\rho_A$, it has nonzero entropy. 

In [13]:
vn_entropy(G_rho_A)

0.6720147574191525

### $\color{green}{\rm Cross-check:}$ 
We compare with the result obtained by exact diagonalization. 

In [14]:
Ising_SvN_exact_diag(L_A = 5, L=10)

0.672014753864282

## Fermionic Gaussian Channel
A fermionic Gaussian channel $\mathcal{E}$ the following Grassmann representation 
$$
\omega\left( {\cal E}(X), \theta\right) ~=~ \int D\mu D\eta\, \exp\Big[ \frac{i}{2}\,\theta^{\rm T}A\,\theta ~+~ i\,\theta^{\rm T}B\,\eta \,+\, i\eta^{\rm T}\mu \Big]\,\omega(X,\mu)
$$
where 
- $X$ is the input fermionic state composed of $2L$ Majorana fermions or equivalently $L$ spins. 
- $A$ and $B$ are complex antisymmetric $2L\times 2L$ matrices. The fermionic Gaussian channel can be completely determined by $A$ and $B$. 

## $\color{purple}{\rm Function:}$ erasure_channel(L = int, L_erasure = int)
This function yields the 

## $\color{purple}{\rm Function:}$ Gaussian_channel(A, B, Grho)
This function compute the new correlation matrix $G^{\mathcal{E}(\rho)}$ after a Gaussian linear map $\mathcal{E}$ acting on $\rho$. 

Input: 
- Grho: the original correlation matrix $G^{\rho}$ for $\rho$
- A, B: matrices in the integral representation of the fermionic Gaussian channel $\mathcal{E}$

Output: 
- the new correlation matrix $G^{\mathcal{E}(\rho)}$

### $\color{green}{\rm Example:}$ 
Consider the erasure channel